**Assignment 2** focuses on the training on a Neural Machine Translation (NMT) system with an attention model.

This is an **individual assignment** and usual rules for plagiarism apply! With this you agree that: "In submitting this work I confirm that it is entirely my own. I acknowledge that I may be invited to online interview if there is any concern in relation to the integrity of my exam." 

**Write comments and documentation.**



## Section 1- Data Collection and Preprocessing 


---


**Task 1  (5 marks)**

---

There are few datasets to train an NMT system available from the OPUS project (http://opus.nlpl.eu/).

*  Download a language pair (preferably European language) and **extract** the file(s) and upload it to CoLab
*  Create a list of lines by splitting the text file at every occurrence accordingly, i.e. source and target language
*  Print number of sentences
*  Limit the number of sentences to 10,000 lines (but more than 5,000 lines)
*  Split the data into train, development and test set
*  Print 100th sentence in original script for source and target language

In [ ]:
import os, sys

from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, LSTM, GRU, Dense, Embedding
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.utils import to_categorical
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
latent_dim = 256

In [ ]:
import numpy as np
import random
from sklearn.model_selection import train_test_split
import pandas as pd
german_sentences = []
english_sentences = []

num_sentences = 10000
#english_file = open("C:/Users/lhaye/Documents/NLP_Assignment_2/CCAligned.de-en.txt", encoding="utf8")
#german_file = open("C:/Users/lhaye/Documents/NLP_Assignment_2/CCAligned.de-en.txt", encoding="utf8")

with open("C:/Users/lhaye/Documents/NLP_Assignment_2/GNOME.de-en_en.txt", encoding="utf8") as english_file:
    for i in range(num_sentences):    
        english_sentences.append(english_file.readline())
        
with open("C:/Users/lhaye/Documents/NLP_Assignment_2/GNOME.de-en_de.txt", encoding="utf8") as german_file:
    for i in range(num_sentences):    
        german_sentences.append(german_file.readline())

#english_file.close()
#german_file.close()

#print(english_sentences[100])
#print(german_sentences[100])

#NOW WE NEED TO SPLIT THE DATA INTO TRAIN, DEVELOPMENT AND TEST
#LETS SAY 70, 15, 15

data_frame = {'English':english_sentences,'German':german_sentences}
data_frame = pd.DataFrame(data_frame)

train, test = train_test_split(data_frame, test_size=0.3)
val, test_final = train_test_split(test, test_size=0.5)

#print(train['English'])
#print(train['German'][2])

#print(train['English'])
#x=train['English'] 

english_train_sent_list = train['English'].to_list()
english_test_sent_list = test_final['English'].to_list()

german_train_sent_list = train['German'].to_list()
german_test_sent_list = test_final['German'].to_list()


for i in range(20):
    i += 1
    #print(i)
    #print(english_sent_list[i])
    #print(german_sent_list[i])

#NOW WE HAVE ALL THE DATA 


**Task 2 (5 marks)** 

---

* Add '<bof\>' to denote beginning of sentence and '<eos\>' to denote the end of the sentence to each target line.
* Perform the pre-processing step of the text.
* Print the last 5 sentences of the preprocessed text.
* Print statistics on the selected dataset:
  * Number of samples
  * Number of unique source language tokens
  * Number of unique target language tokens
  * Max sequence length of source language
  * Max sequence length of target language
  * Source Vocabulary
  * Target Vocabulary





In [ ]:
import nltk
#nltk.download('punkt')
from nltk.tokenize import word_tokenize
import re 

#OKAY SO LETS DO IT ON THE TRAINING DATA 
english_text_list = []
german_text_list_input = []
german_text_list_output = []
english_text_list_nottok = []
german_input_text_list_nottok = []
german_output_text_list_nottok = []
#WE USE SETS BECAUSE IT DOESN'T DO DUPLICATES
english_words = set()
german_words = set()
english_words_dict = {}
german_words_dict = {}


num_samples_train = 7000
for sent_idx in range(num_samples_train):
    
    #GET THE ENGLISH AND GERMAN SENTENCE FOR THE INDEX
    english_sentence = english_train_sent_list[sent_idx]
    german_sentence_input = german_train_sent_list[sent_idx]
    german_sentence_output = german_train_sent_list[sent_idx]

    #SET THE WORDS TO BE LOWER CASE
    english_sentence = english_sentence.lower()
    german_sentence_input = german_sentence_input.lower()
    
    #print(english_sentence)
    
    #NOW REMOVE NUMBERS
    english_sentence = re.sub(r'\d+', '', english_sentence)
    german_sentence_input = re.sub(r'\d+', '', german_sentence_input)
    german_sentence_output = re.sub(r'\d+', '', german_sentence_input)


    #NOW WE NEED TO ADD THE '<bof>' TO THE START AND '<eof>' TO THE END OF THE GERMAN TEXT 
    #german_sentence_input.insert(0, '<bof>')
    #german_sentence_tok_output.append('<eof>')
    
    german_sentence_input = '<sos> ' + german_sentence_input
    german_sentence_output = german_sentence_output + ' <eos>'
    
    #english_sentence = [word for word in english_sentence if word.isalnum()]
    #german_sentence_input = [word for word in german_sentence_input if word.isalnum()]
    #german_sentence_output = [word for word in german_sentence_output if word.isalnum()]
    
    print(english_sentence)
    
    english_sentence = english_sentence.replace('\n', '')
    german_sentence_input = german_sentence_input.replace('\n', '')
    german_sentence_output = german_sentence_output.replace('\n', '')

    
    #WE SHOULD ONLY BE WORKING WITH THESE 
    english_text_list_nottok.append(english_sentence)
    german_input_text_list_nottok.append(german_sentence_input)
    german_output_text_list_nottok.append(german_sentence_output)

    #TOKENIZE THE WORDS IN THE SENTENCE 
    #english_sentence_tok = word_tokenize(english_sentence)
    #german_sentence_tok_input = word_tokenize(german_sentence_input)
    #german_sentence_tok_output = word_tokenize(german_sentence_output)

    #REMOVE ALL WORDS/TOKENS THAT DO NOT CONTAIN CHARACTERS
    #english_sentence_tok = [word for word in english_sentence_tok if word.isalnum()]
    #german_sentence_tok_input = [word for word in german_sentence_tok_input if word.isalnum()]
    #german_sentence_tok_output = [word for word in german_sentence_tok_output if word.isalnum()]

    #german_sentence_tok_input = '<bof>' + german_sentence_tok_input
    #german_sentence_tok_output = german_sentence_tok_output + '<eof>'
    
    #WE NEED TO DO THE SAME HERE EXCEPT WITH A DICT 
    #{word: occurances}
    #for word in english_sentence_tok:
        #if word not in english_words_dict:
          #english_words_dict[word] = 1
        #else:
            #english_words_dict[word] += 1
    #for word in german_sentence_tok_input:
        #if word not in german_words_dict:
          #german_words_dict[word] = 1
        #else:
            #german_words_dict[word] += 1
       

    #PRINT THE LAST 5 
    #if (sent_idx > (num_samples_train-5) and (sent_idx <= num_samples_train)):
        #print(english_sentence_tok)
        #print(german_sentence_tok_input)
        #print(german_sentence_tok_output)
        
    #ADD THE SENTENCE TO A LIST
    #english_text_list.append(english_sentence_tok)
    #german_text_list_input.append(german_sentence_tok_input)
    #german_text_list_output.append(german_sentence_tok_output)

    #CHECK IF THE WORD IS ALREADY IN THE LIST OF UNIQUE WORDS AND ADD IF NOT
    #for word in english_text_list_nottok:
        #if word not in english_words:
          #english_words.add(word)
    #for word in german_sentence_tok_input:
        #if word not in german_words:
          #german_words.add(word)
    #for word in german_sentence_tok_output:
        #if word not in german_words:
          #german_words.add(word)      
#print(english_words_dict['computer']) 
#print(german_words) 


In [ ]:
#WE SHOULD ONLY BE WORKING WITH THESE 
#english_text_list_nottok
#german_input_text_list_nottok
#german_output_text_list_nottok

num_samples = len(english_text_list_nottok)
#print(num_samples)
MAX_NUM_WORDS = 50000
#print(german_input_text_list_nottok)
#print(german_output_text_list_nottok)
#print(english_text_list_nottok)

print(english_text_list_nottok[8])
print(german_output_text_list_nottok[8])
print(german_input_text_list_nottok[8])

In [ ]:
print(german_output_text_list_nottok)

In [ ]:
input_tokenizer = Tokenizer(num_words=MAX_NUM_WORDS)
input_tokenizer.fit_on_texts(english_text_list_nottok)
input_integer_seq = input_tokenizer.texts_to_sequences(english_text_list_nottok)

word2idx_inputs = input_tokenizer.word_index
print('Total unique words in the input: %s' % len(word2idx_inputs))

max_input_len = max(len(sen) for sen in input_integer_seq)
print("Length of longest sentence in input: %g" % max_input_len)

print(word2idx_inputs)

In [ ]:
print(input_integer_seq[172])
print(english_text_list_nottok[172])

In [ ]:
output_tokenizer = Tokenizer(num_words=MAX_NUM_WORDS, filters='')
output_tokenizer.fit_on_texts(german_output_text_list_nottok + german_input_text_list_nottok)
output_integer_seq = output_tokenizer.texts_to_sequences(german_output_text_list_nottok)
output_input_integer_seq = output_tokenizer.texts_to_sequences(german_input_text_list_nottok)

word2idx_outputs = output_tokenizer.word_index
print('Total unique words in the output: %s' % len(word2idx_outputs))

num_words_output = len(word2idx_outputs) + 1
max_out_len = max(len(sen) for sen in output_integer_seq)
print("Length of longest sentence in the output: %g" % max_out_len)

print(output_input_integer_seq)

In [ ]:
encoder_input_sequences = pad_sequences(input_integer_seq, maxlen=max_input_len)
print("encoder_input_sequences.shape:", encoder_input_sequences.shape)
print("encoder_input_sequences[172]:", encoder_input_sequences[172])
print(english_train_sent_list[172])
print(input_integer_seq[172])

encoder_input_sequences.shape: (7000, 125)
encoder_input_sequences[172]: [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 221 108]
Quick Select

[221, 108]


In [ ]:
decoder_input_sequences = pad_sequences(output_input_integer_seq, maxlen=max_out_len, padding='post')
print("decoder_input_sequences.shape:", decoder_input_sequences.shape)
print("decoder_input_sequences[172]:", decoder_input_sequences[172])

decoder_input_sequences.shape: (7000, 124)
decoder_input_sequences[172]: [  2 962   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]


In [ ]:
decoder_output_sequences = pad_sequences(output_integer_seq, maxlen=max_out_len, padding='post')
print("decoder_input_sequences.shape:", decoder_output_sequences.shape)
print("decoder_input_sequences[172]:", decoder_output_sequences[172])


decoder_input_sequences.shape: (7000, 124)
decoder_input_sequences[172]: [962   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]


In [ ]:
print(word2idx_outputs["<sos>"])
print(word2idx_outputs["<eos>"])

2
1


In [ ]:
from numpy import array
from numpy import asarray
from numpy import zeros

embeddings_dictionary = dict()

glove_file = open('./glove.6B.100d.txt', encoding="utf8")

for line in glove_file:
    records = line.split()
    word = records[0]
    vector_dimensions = asarray(records[1:], dtype='float32')
    embeddings_dictionary[word] = vector_dimensions
glove_file.close()

In [ ]:
#print(english_token_index)
num_words = len(word2idx_inputs) + 1
embedding_matrix = zeros((num_words, 100))
for word, index in word2idx_inputs.items():
    embedding_vector = embeddings_dictionary.get(word)
    if embedding_vector is not None:
        embedding_matrix[index] = embedding_vector
        
print(embeddings_dictionary["computer"])


[-1.6298e-01  3.0141e-01  5.7978e-01  6.6548e-02  4.5835e-01 -1.5329e-01
  4.3258e-01 -8.9215e-01  5.7747e-01  3.6375e-01  5.6524e-01 -5.6281e-01
  3.5659e-01 -3.6096e-01 -9.9662e-02  5.2753e-01  3.8839e-01  9.6185e-01
  1.8841e-01  3.0741e-01 -8.7842e-01 -3.2442e-01  1.1202e+00  7.5126e-02
  4.2661e-01 -6.0651e-01 -1.3893e-01  4.7862e-02 -4.5158e-01  9.3723e-02
  1.7463e-01  1.0962e+00 -1.0044e+00  6.3889e-02  3.8002e-01  2.1109e-01
 -6.6247e-01 -4.0736e-01  8.9442e-01 -6.0974e-01 -1.8577e-01 -1.9913e-01
 -6.9226e-01 -3.1806e-01 -7.8565e-01  2.3831e-01  1.2992e-01  8.7721e-02
  4.3205e-01 -2.2662e-01  3.1549e-01 -3.1748e-01 -2.4632e-03  1.6615e-01
  4.2358e-01 -1.8087e+00 -3.6699e-01  2.3949e-01  2.5458e+00  3.6111e-01
  3.9486e-02  4.8607e-01 -3.6974e-01  5.7282e-02 -4.9317e-01  2.2765e-01
  7.9966e-01  2.1428e-01  6.9811e-01  1.1262e+00 -1.3526e-01  7.1972e-01
 -9.9605e-04 -2.6842e-01 -8.3038e-01  2.1780e-01  3.4355e-01  3.7731e-01
 -4.0251e-01  3.3124e-01  1.2576e+00 -2.7196e-01 -8

In [ ]:
#WE NEED TO FIX THOSE EMBEDDINGS 
embedding_layer = Embedding(num_words, 100, weights=[embedding_matrix], input_length=max_input_len)
#embedding_layer = Embedding(num_english_tokens, 300, input_length=max_english_seq_length)

print(embedding_matrix)

[[ 0.          0.          0.         ...  0.          0.
   0.        ]
 [-0.038194   -0.24487001  0.72812003 ... -0.1459      0.82779998
   0.27061999]
 [-0.1529     -0.24279     0.89837003 ... -0.59100002  1.00390005
   0.20664001]
 ...
 [ 0.07401     0.50411999  0.21244    ... -0.55091     0.42706999
   0.30928001]
 [-0.96662003  0.64036     0.27232    ... -0.1137      0.51686001
   0.40193999]
 [ 0.083247    0.41929999  0.35538    ...  0.42758    -0.29018
   0.86532998]]


NOW ONTO THE MODEL

In [ ]:
decoder_targets_one_hot = np.zeros((
        len(english_text_list_nottok),
        (max_out_len),
        (num_words_output)
    ),
    dtype='float32'
)

In [ ]:
print(decoder_targets_one_hot.shape)

(7000, 124, 3596)


In [ ]:
for i, d in enumerate(decoder_output_sequences):
    for t, word in enumerate(d):
        decoder_targets_one_hot[i, t, word] = 1

In [ ]:
encoder_inputs_placeholder = Input(shape=(max_input_len,))
x = embedding_layer(encoder_inputs_placeholder)
encoder = LSTM(latent_dim, return_state=True)

encoder_outputs, h, c = encoder(x)
encoder_states = [h, c]

In [ ]:
decoder_inputs_placeholder = Input(shape=((max_out_len),))

decoder_embedding = Embedding(num_words_output, latent_dim)
decoder_inputs_x = decoder_embedding(decoder_inputs_placeholder)

decoder_lstm = LSTM(latent_dim, return_sequences=True, return_state=True)
decoder_outputs, _, _ = decoder_lstm(decoder_inputs_x, initial_state=encoder_states)

In [ ]:
decoder_dense = Dense(num_words_output, activation='softmax')
decoder_outputs = decoder_dense(decoder_outputs)

In [ ]:
model = Model([encoder_inputs_placeholder,
  decoder_inputs_placeholder], decoder_outputs)
model.compile(
    optimizer='rmsprop',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [ ]:
model.load_weights('./seq2seq_eng-de.h5')

In [ ]:
r = model.fit(
    [encoder_input_sequences, decoder_input_sequences],
    decoder_targets_one_hot,
    batch_size=64,
    epochs=20,
    validation_split=0.1,
)

Epoch 1/20
99/99 [==============================] - 245s 2s/step - loss: 1.7255 - accuracy: 0.8727 - val_loss: 0.4993 - val_accuracy: 0.9239
Epoch 2/20
99/99 [==============================] - 228s 2s/step - loss: 0.4493 - accuracy: 0.9304 - val_loss: 0.4481 - val_accuracy: 0.9283
Epoch 3/20
99/99 [==============================] - 226s 2s/step - loss: 0.3983 - accuracy: 0.9348 - val_loss: 0.4026 - val_accuracy: 0.9330
Epoch 4/20
99/99 [==============================] - 217s 2s/step - loss: 0.3626 - accuracy: 0.9376 - val_loss: 0.3682 - val_accuracy: 0.9369
Epoch 5/20
99/99 [==============================] - 222s 2s/step - loss: 0.3238 - accuracy: 0.9421 - val_loss: 0.3332 - val_accuracy: 0.9418
Epoch 6/20
99/99 [==============================] - 217s 2s/step - loss: 0.2834 - accuracy: 0.9477 - val_loss: 0.3088 - val_accuracy: 0.9459
Epoch 7/20
99/99 [==============================] - 212s 2s/step - loss: 0.2593 - accuracy: 0.9507 - val_loss: 0.2757 - val_accuracy: 0.9501
Epoch 8/20
99

In [ ]:
model.save('./seq2seq_eng-de_new2.h5')

In [ ]:
encoder_model = Model(encoder_inputs_placeholder, encoder_states)

In [ ]:
decoder_state_input_h = Input(shape=(latent_dim,))
decoder_state_input_c = Input(shape=(latent_dim,))
decoder_states_inputs = [decoder_state_input_h, decoder_state_input_c]

In [ ]:
decoder_inputs_single = Input(shape=(1,))
decoder_inputs_single_x = decoder_embedding(decoder_inputs_single)

In [ ]:
decoder_outputs, h, c = decoder_lstm(decoder_inputs_single_x, initial_state=decoder_states_inputs)

In [ ]:
decoder_states = [h, c]
decoder_outputs = decoder_dense(decoder_outputs)

In [ ]:
decoder_model = Model(
    [decoder_inputs_single] + decoder_states_inputs,
    [decoder_outputs] + decoder_states
)

In [ ]:
idx2word_input = {v:k for k, v in word2idx_inputs.items()}
idx2word_target = {v:k for k, v in word2idx_outputs.items()}
print(idx2word_target)

In [ ]:
def translate_sentence(input_seq):
    
    states_value = encoder_model.predict(input_seq)
    target_seq = np.zeros((1, 1))
    target_seq[0, 0] = word2idx_outputs['<sos>']
    eos = word2idx_outputs['<eos>']
    output_sentence = []

    for _ in range(max_input_len):

        output_tokens, h, c = decoder_model.predict([target_seq] + states_value)
        idx = np.argmax(output_tokens[0, 0, :])
        
        #print(idx)
        #print(eos)
        if eos == idx:
            break

        word = ''
        
        if idx > 0:
            word = idx2word_target[idx]
            output_sentence.append(word)

        target_seq[0, 0] = idx
        states_value = [h, c]

    return ' '.join(output_sentence)

In [ ]:
#i = np.random.choice(len(english_text_list_nottok))
#print(english_text_list_nottok[i])
#input_seq = encoder_input_sequences[i:i+1]
#print(encoder_input_sequences[i:i+1])
#translation = translate_sentence(input_seq)
#print('-')
#print('Input:', english_text_list_nottok[i])
#print('output:', german_input_text_list_nottok[i])

#print('Response:', translation)

for i in range(10):
    index = i + 1
    input_seq = encoder_input_sequences[index:index+1]
    #print(input_seq)
    translation = translate_sentence(input_seq)
    
    print("---------------------------------------------------------------")
    print("Sentence Number: " , index)
    print('English Input Sentence: ', english_text_list_nottok[index])
    print('Actual German Translation: ' , german_input_text_list_nottok[index])
    print('Perdicted Translation: ', translation)
    #print('Response:', translation)

---------------------------------------------------------------
Sentence Number:  1
English Input Sentence:  the border color of the highlight box
Actual German Translation:  <sos> die randfarbe der hervorhebenden box
Perdicted Translation:  die randfarbe der hervorhebenden box
---------------------------------------------------------------
Sentence Number:  2
English Input Sentence:  unknown
Actual German Translation:  <sos> unbekannt
Perdicted Translation:  unbekannt
---------------------------------------------------------------
Sentence Number:  3
English Input Sentence:  some of accerciser's elements, such as the global hotkey ctrl+alt+/, highlight a specific widget in a target application. the highlighting duration, border color, and fill color can be customized via the preferences dialog, under the "highlighting" tab.
Actual German Translation:  <sos> ein paar von den elementen von accerciser, z.b. die globalen tastenkürzel strg+alt+/, markieren eine spezielle funktion einer zie

In [ ]:
#OKAY SO NOW WE NEED TO 
#LOOP THROUGH THE LIST OF SENTENCES

#print(len(english_test_sent_list))
indexes = []
for i in range(len(english_test_sent_list)):
    
    index = []
    #WE NEED TO TOKENIZE THE INPUT AND REMOVE THE /N
    
    tokens = nltk.word_tokenize(english_test_sent_list[i])
    tokens=[word.lower() for word in tokens if word.isalpha()]
    
    for token in tokens:
        if token not in word2idx_inputs:
            print("Word isn't in this")
        else:
            idx = word2idx_inputs[token]
            index.append(idx)
                
    indexes.append(index)
    
    #input_integer_seq = input_tokenizer.texts_to_sequences(english_text_list_nottok)
encoder_input_sequences_new = pad_sequences(indexes, maxlen=max_input_len)
print(encoder_input_sequences_new)

translated_sentences = []
actual_sentences = []

for i in range(len(english_test_sent_list)):
    translation = translate_sentence(encoder_input_sequences_new[i:i+1])
    #print("---------------------------------------------------------------")
    #print("Sentence Number: " , i)
    #print('English Input Sentence: ', english_test_sent_list[i])
    #print('Actual German Translation: ' , german_test_sent_list[i])
    #print('Perdicted Translation: ', translation)
    actual_sentences.append(german_test_sent_list[i])
    translated_sentences.append(translation)
    

Word isn't in this
Word isn't in this
Word isn't in this
Word isn't in this
Word isn't in this
Word isn't in this
Word isn't in this
Word isn't in this
[[   0    0    0 ...    0    0 1361]
 [   0    0    0 ...    0    0 1633]
 [   0    0    0 ...    0    0  779]
 ...
 [   0    0    0 ...    7   21   99]
 [   0    0    0 ...    1 1932 1933]
 [   0    0    0 ...    0    0  835]]


In [ ]:
print(translated_sentences[1494])
print(actual_sentences[1494])
print(english_test_sent_list[1494])
#OKAY SO NOW WE NEED TO CALCULATE THE BLEU SCORE 

for i in range(len(actual_sentences)):
    actual_sentences[i] = actual_sentences[i].lower()
    
print(actual_sentences[1494])




fokusobjekt %s hat eine tabellenschnittstelle, aber keine auswahlschnittstellebutton has focused state without focusable state
Fokusobjekt %s hat eine Tabellenschnittstelle, aber keine Auswahlschnittstellebutton has focused state without focusable state

focusable %s has a table interface, but not a selection interface

fokusobjekt %s hat eine tabellenschnittstelle, aber keine auswahlschnittstellebutton has focused state without focusable state



In [ ]:
from nltk.translate.bleu_score import sentence_bleu

scores = 0.00
num = 0

for i in range(len(actual_sentences)):
    
    num += 1
    
    tokens_actual = actual_sentences[i].split()
    tokens_translated = translated_sentences[i].split()
   
    tokens_actual = [tokens_actual]

    score = sentence_bleu(tokens_actual, tokens_translated, weights=(1, 0, 0, 0))
    scores += score
    
print("This is the BLEU score for the Test Set: " , (scores/num))


This is the BLEU score for the Test Set:  0.7099551247027194


**Task 3 (5 marks)** 

---

---

*  Assign each unique word an integer value (5 marks).
*  Create word embedding for your vocabulary using pre-trained embeddings, for example GloVe or fastText (10 marks) (https://nlp.stanford.edu/projects/glove/ , https://fasttext.cc/docs/en/english-vectors.html)
* Print the first line of the embeddings (see below) 

## Section 2 Translation Model training



---



**Task 4 (15 marks)**
* Provide code for the encoder using Keras LSTM (5 marks)
* Provide code for the decoder using Keras LSTM (5 marks)
* Train the sequence2sequence (encoder-decoder) model (5 marks) 


## Section 3 Testing

---

**Task 5 (20 marks)**

* Use the trained model to translate the text from the source into the target language (10 marks). 
* Use the test/evaluation set (see Section 1) and perform an automatic evaluation with the BLEU metric (10 marks). 
You can use the NLTK library to calculate BLEU.

# Section 4 Attention

---



**Task 5 (40 Marks)** Sequence2Sequence

* Extend the existing Seq2Seq model with an attention mechanism [Discussed in Class]
* Create sequence2sequence model with attention (15 marks)
* Train the model with the same data from Section 1 (10 marks)
* Translate the evaluation set using the sequence2sequence attention model (10 marks)
* Evaluate the translations made with the sequence2sequence attention model and compare it with the model without attention using BLEU (5 marks)

In [ ]:
#Your code goes here